//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

export class Client {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? `http://${window.location.hostname}`;
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    getPolls(body: BaseRequest | undefined): Promise<GetPollsResponse> {
        let url_ = this.baseUrl + "/api/Polls/GetPolls";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetPolls(_response);
        });
    }

    protected processGetPolls(response: Response): Promise<GetPollsResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
                let result200: any = null;
                let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = GetPollsResponse.fromJS(resultData200);
                return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<GetPollsResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    createPoll(body: CreatePollRequest | undefined): Promise<BaseResponse> {
        let url_ = this.baseUrl + "/api/Polls/CreatePoll";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreatePoll(_response);
        });
    }

    protected processCreatePoll(response: Response): Promise<BaseResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
                let result200: any = null;
                let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = BaseResponse.fromJS(resultData200);
                return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<BaseResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    deletePoll(body: DeletePollRequest | undefined): Promise<BaseResponse> {
        let url_ = this.baseUrl + "/api/Polls/DeletePoll";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDeletePoll(_response);
        });
    }

    protected processDeletePoll(response: Response): Promise<BaseResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
                let result200: any = null;
                let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = BaseResponse.fromJS(resultData200);
                return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<BaseResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    getPoll(body: GetPollRequest | undefined): Promise<GetPollResponse> {
        let url_ = this.baseUrl + "/api/Polls/GetPoll";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetPoll(_response);
        });
    }

    protected processGetPoll(response: Response): Promise<GetPollResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
                let result200: any = null;
                let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = GetPollResponse.fromJS(resultData200);
                return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<GetPollResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    processPoll(body: ProcessPollRequest | undefined): Promise<BaseResponse> {
        let url_ = this.baseUrl + "/api/Polls/ProcessPoll";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processProcessPoll(_response);
        });
    }

    protected processProcessPoll(response: Response): Promise<BaseResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
                let result200: any = null;
                let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = BaseResponse.fromJS(resultData200);
                return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<BaseResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    pollStatistic(body: GetPollRequest | undefined): Promise<PollStatisticResponse> {
        let url_ = this.baseUrl + "/api/Polls/PollStatistic";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processPollStatistic(_response);
        });
    }

    protected processPollStatistic(response: Response): Promise<PollStatisticResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
                let result200: any = null;
                let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = PollStatisticResponse.fromJS(resultData200);
                return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<PollStatisticResponse>(null as any);
    }
}

export class Answer implements IAnswer {
    text?: string | undefined;
    answerId?: number;

    constructor(data?: IAnswer) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.text = _data["text"];
            this.answerId = _data["answerId"];
        }
    }

    static fromJS(data: any): Answer {
        data = typeof data === 'object' ? data : {};
        let result = new Answer();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["text"] = this.text;
        data["answerId"] = this.answerId;
        return data;
    }
}

export interface IAnswer {
    text?: string | undefined;
    answerId?: number;
}

export class AnsweredQuestion implements IAnsweredQuestion {
    questionId?: number;
    selectedAnswer?: number;

    constructor(data?: IAnsweredQuestion) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.questionId = _data["questionId"];
            this.selectedAnswer = _data["selectedAnswer"];
        }
    }

    static fromJS(data: any): AnsweredQuestion {
        data = typeof data === 'object' ? data : {};
        let result = new AnsweredQuestion();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["questionId"] = this.questionId;
        data["selectedAnswer"] = this.selectedAnswer;
        return data;
    }
}

export interface IAnsweredQuestion {
    questionId?: number;
    selectedAnswer?: number;
}

export class BaseRequest implements IBaseRequest {
    apiKey?: string | undefined;

    constructor(data?: IBaseRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.apiKey = _data["apiKey"];
        }
    }

    static fromJS(data: any): BaseRequest {
        data = typeof data === 'object' ? data : {};
        let result = new BaseRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["apiKey"] = this.apiKey;
        return data;
    }
}

export interface IBaseRequest {
    apiKey?: string | undefined;
}

export class BaseResponse implements IBaseResponse {
    success?: boolean;
    errorMessage?: string | undefined;

    constructor(data?: IBaseResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.success = _data["success"];
            this.errorMessage = _data["errorMessage"];
        }
    }

    static fromJS(data: any): BaseResponse {
        data = typeof data === 'object' ? data : {};
        let result = new BaseResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["success"] = this.success;
        data["errorMessage"] = this.errorMessage;
        return data;
    }
}

export interface IBaseResponse {
    success?: boolean;
    errorMessage?: string | undefined;
}

export class CreatePollRequest implements ICreatePollRequest {
    apiKey?: string | undefined;
    title?: string | undefined;
    description?: string | undefined;
    questions?: Question[] | undefined;

    constructor(data?: ICreatePollRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.apiKey = _data["apiKey"];
            this.title = _data["title"];
            this.description = _data["description"];
            if (Array.isArray(_data["questions"])) {
                this.questions = [] as any;
                for (let item of _data["questions"])
                    this.questions!.push(Question.fromJS(item));
            }
        }
    }

    static fromJS(data: any): CreatePollRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreatePollRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["apiKey"] = this.apiKey;
        data["title"] = this.title;
        data["description"] = this.description;
        if (Array.isArray(this.questions)) {
            data["questions"] = [];
            for (let item of this.questions)
                data["questions"].push(item.toJSON());
        }
        return data;
    }
}

export interface ICreatePollRequest {
    apiKey?: string | undefined;
    title?: string | undefined;
    description?: string | undefined;
    questions?: Question[] | undefined;
}

export class DeletePollRequest implements IDeletePollRequest {
    apiKey?: string | undefined;
    pollId?: number;

    constructor(data?: IDeletePollRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.apiKey = _data["apiKey"];
            this.pollId = _data["pollId"];
        }
    }

    static fromJS(data: any): DeletePollRequest {
        data = typeof data === 'object' ? data : {};
        let result = new DeletePollRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["apiKey"] = this.apiKey;
        data["pollId"] = this.pollId;
        return data;
    }
}

export interface IDeletePollRequest {
    apiKey?: string | undefined;
    pollId?: number;
}

export class GetPollRequest implements IGetPollRequest {
    apiKey?: string | undefined;
    pollId?: number;

    constructor(data?: IGetPollRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.apiKey = _data["apiKey"];
            this.pollId = _data["pollId"];
        }
    }

    static fromJS(data: any): GetPollRequest {
        data = typeof data === 'object' ? data : {};
        let result = new GetPollRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["apiKey"] = this.apiKey;
        data["pollId"] = this.pollId;
        return data;
    }
}

export interface IGetPollRequest {
    apiKey?: string | undefined;
    pollId?: number;
}

export class GetPollResponse implements IGetPollResponse {
    success?: boolean;
    errorMessage?: string | undefined;
    poll?: Poll;
    questions?: Question[] | undefined;

    constructor(data?: IGetPollResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.success = _data["success"];
            this.errorMessage = _data["errorMessage"];
            this.poll = _data["poll"] ? Poll.fromJS(_data["poll"]) : <any>undefined;
            if (Array.isArray(_data["questions"])) {
                this.questions = [] as any;
                for (let item of _data["questions"])
                    this.questions!.push(Question.fromJS(item));
            }
        }
    }

    static fromJS(data: any): GetPollResponse {
        data = typeof data === 'object' ? data : {};
        let result = new GetPollResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["success"] = this.success;
        data["errorMessage"] = this.errorMessage;
        data["poll"] = this.poll ? this.poll.toJSON() : <any>undefined;
        if (Array.isArray(this.questions)) {
            data["questions"] = [];
            for (let item of this.questions)
                data["questions"].push(item.toJSON());
        }
        return data;
    }
}

export interface IGetPollResponse {
    success?: boolean;
    errorMessage?: string | undefined;
    poll?: Poll;
    questions?: Question[] | undefined;
}

export class GetPollsResponse implements IGetPollsResponse {
    success?: boolean;
    errorMessage?: string | undefined;
    polls?: Poll[] | undefined;

    constructor(data?: IGetPollsResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.success = _data["success"];
            this.errorMessage = _data["errorMessage"];
            if (Array.isArray(_data["polls"])) {
                this.polls = [] as any;
                for (let item of _data["polls"])
                    this.polls!.push(Poll.fromJS(item));
            }
        }
    }

    static fromJS(data: any): GetPollsResponse {
        data = typeof data === 'object' ? data : {};
        let result = new GetPollsResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["success"] = this.success;
        data["errorMessage"] = this.errorMessage;
        if (Array.isArray(this.polls)) {
            data["polls"] = [];
            for (let item of this.polls)
                data["polls"].push(item.toJSON());
        }
        return data;
    }
}

export interface IGetPollsResponse {
    success?: boolean;
    errorMessage?: string | undefined;
    polls?: Poll[] | undefined;
}

export class Poll implements IPoll {
    pollId?: number;
    title?: string | undefined;
    description?: string | undefined;
    doneByUser?: boolean;
    readonly ownedByUser?: boolean;

    constructor(data?: IPoll) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.pollId = _data["pollId"];
            this.title = _data["title"];
            this.description = _data["description"];
            this.doneByUser = _data["doneByUser"];
            (<any>this).ownedByUser = _data["ownedByUser"];
        }
    }

    static fromJS(data: any): Poll {
        data = typeof data === 'object' ? data : {};
        let result = new Poll();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["pollId"] = this.pollId;
        data["title"] = this.title;
        data["description"] = this.description;
        data["doneByUser"] = this.doneByUser;
        data["ownedByUser"] = this.ownedByUser;
        return data;
    }
}

export interface IPoll {
    pollId?: number;
    title?: string | undefined;
    description?: string | undefined;
    doneByUser?: boolean;
    ownedByUser?: boolean;
}

export class PollStatisticResponse implements IPollStatisticResponse {
    success?: boolean;
    errorMessage?: string | undefined;
    pollTitle?: string | undefined;
    pollDescription?: string | undefined;
    questions?: UserQuestion[] | undefined;

    constructor(data?: IPollStatisticResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.success = _data["success"];
            this.errorMessage = _data["errorMessage"];
            this.pollTitle = _data["pollTitle"];
            this.pollDescription = _data["pollDescription"];
            if (Array.isArray(_data["questions"])) {
                this.questions = [] as any;
                for (let item of _data["questions"])
                    this.questions!.push(UserQuestion.fromJS(item));
            }
        }
    }

    static fromJS(data: any): PollStatisticResponse {
        data = typeof data === 'object' ? data : {};
        let result = new PollStatisticResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["success"] = this.success;
        data["errorMessage"] = this.errorMessage;
        data["pollTitle"] = this.pollTitle;
        data["pollDescription"] = this.pollDescription;
        if (Array.isArray(this.questions)) {
            data["questions"] = [];
            for (let item of this.questions)
                data["questions"].push(item.toJSON());
        }
        return data;
    }
}

export interface IPollStatisticResponse {
    success?: boolean;
    errorMessage?: string | undefined;
    pollTitle?: string | undefined;
    pollDescription?: string | undefined;
    questions?: UserQuestion[] | undefined;
}

export class ProcessPollRequest implements IProcessPollRequest {
    apiKey?: string | undefined;
    pollId?: number;
    answereds?: AnsweredQuestion[] | undefined;

    constructor(data?: IProcessPollRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.apiKey = _data["apiKey"];
            this.pollId = _data["pollId"];
            if (Array.isArray(_data["answereds"])) {
                this.answereds = [] as any;
                for (let item of _data["answereds"])
                    this.answereds!.push(AnsweredQuestion.fromJS(item));
            }
        }
    }

    static fromJS(data: any): ProcessPollRequest {
        data = typeof data === 'object' ? data : {};
        let result = new ProcessPollRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["apiKey"] = this.apiKey;
        data["pollId"] = this.pollId;
        if (Array.isArray(this.answereds)) {
            data["answereds"] = [];
            for (let item of this.answereds)
                data["answereds"].push(item.toJSON());
        }
        return data;
    }
}

export interface IProcessPollRequest {
    apiKey?: string | undefined;
    pollId?: number;
    answereds?: AnsweredQuestion[] | undefined;
}

export class Question implements IQuestion {
    questionId?: number;
    title?: string | undefined;
    answers?: Answer[] | undefined;

    constructor(data?: IQuestion) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.questionId = _data["questionId"];
            this.title = _data["title"];
            if (Array.isArray(_data["answers"])) {
                this.answers = [] as any;
                for (let item of _data["answers"])
                    this.answers!.push(Answer.fromJS(item));
            }
        }
    }

    static fromJS(data: any): Question {
        data = typeof data === 'object' ? data : {};
        let result = new Question();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["questionId"] = this.questionId;
        data["title"] = this.title;
        if (Array.isArray(this.answers)) {
            data["answers"] = [];
            for (let item of this.answers)
                data["answers"].push(item.toJSON());
        }
        return data;
    }
}

export interface IQuestion {
    questionId?: number;
    title?: string | undefined;
    answers?: Answer[] | undefined;
}

export class UserQuestion implements IUserQuestion {
    question?: string | undefined;
    answers?: UserQuestionAnswer[] | undefined;

    constructor(data?: IUserQuestion) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.question = _data["question"];
            if (Array.isArray(_data["answers"])) {
                this.answers = [] as any;
                for (let item of _data["answers"])
                    this.answers!.push(UserQuestionAnswer.fromJS(item));
            }
        }
    }

    static fromJS(data: any): UserQuestion {
        data = typeof data === 'object' ? data : {};
        let result = new UserQuestion();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["question"] = this.question;
        if (Array.isArray(this.answers)) {
            data["answers"] = [];
            for (let item of this.answers)
                data["answers"].push(item.toJSON());
        }
        return data;
    }
}

export interface IUserQuestion {
    question?: string | undefined;
    answers?: UserQuestionAnswer[] | undefined;
}

export class UserQuestionAnswer implements IUserQuestionAnswer {
    answer?: string | undefined;
    count?: number;

    constructor(data?: IUserQuestionAnswer) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.answer = _data["answer"];
            this.count = _data["count"];
        }
    }

    static fromJS(data: any): UserQuestionAnswer {
        data = typeof data === 'object' ? data : {};
        let result = new UserQuestionAnswer();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["answer"] = this.answer;
        data["count"] = this.count;
        return data;
    }
}

export interface IUserQuestionAnswer {
    answer?: string | undefined;
    count?: number;
}

export class ApiException extends Error {
    message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}